1. The np.append() function in NumPy is used to append values to the end of an array along a specified axis. It takes three main arguments: the array to which the values will be appended, the values to append, and the axis along which the values will be appended.
Here's the syntax of the np.append() function :-
>>> np.append(arr, values, axis=None)
    arr: The array to which the values will be appended.
    values: The values to append. It can be a scalar, an array-like object, or another array.
    axis (optional): The axis along which the values will be appended. If not specified, the array is flattened before appending the values.
    The np.append() function returns a new array with the appended values.
Note that using np.append() repeatedly in a loop to grow an array can be inefficient, as it creates a new array each time. In such cases, it is generally more efficient to preallocate the array and fill it with values using indexing.

2. 
The np.squeeze() function in NumPy is used to remove single-dimensional entries (dimensions with size 1) from an array. It returns a new array with all the single-dimensional dimensions removed.
Here's the syntax of the np.squeeze() function :- 
>>> np.squeeze(a, axis=None)
    a: The input array from which single-dimensional entries will be removed.
    axis (optional): The axis or axes along which to remove single-dimensional entries. If specified, only the dimensions with size 1 along the specified axis or axes will be removed. If not specified, all single-dimensional entries will be removed.
    The np.squeeze() function returns a new array with the single-dimensional entries removed. If no single-dimensional entries are present, it returns the original array itself.
The np.squeeze() function is useful in situations where you want to remove extra dimensions that have size 1, making the array more compact and easier to work with.

1. Two randomly generated arrays are given:

image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).

In [3]:
import numpy as np
 
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
 
image1 = np.expand_dims(image1, axis=0)
image2 = np.expand_dims(image2, axis=0)
 
images = np.append(image1, image2, axis=0)

2. The following array is given:

A = np.array([[[1, 2, 3] , [6, 3, 2]]])

Shape of this array is (1, 2, 3). Remove the unnecessary first dimension and extract (2, 3) array and print it to the console as shown below.

In [5]:
import numpy as np
A = np.array([[[1, 2, 3] , [6, 3, 2]]])
print(np.squeeze(A))

[[1 2 3]
 [6 3 2]]


3. The following array is given:

A = np.array([[0.4] , [0.9] , [0.5] , [0.6]])

Shape of this array is (4, 1). Remove the unnecessary dimension and extract (4, ) array and print result to the console.

In [7]:
import numpy as np
A = np.array([[0.4] , [0.9] , [0.5] , [0.6]])
print(np.squeeze(A))

[0.4 0.9 0.5 0.6]
(4, 1)
