Let's do some :slicing"

1. The following array is given:

array([[ 0,  1,  2,  3] , [ 4,  5,  6,  7] , [ 8,  9, 10, 11]])

Using the slice operator, transform this array into the following:

array([[ 3,  2,  1,  0] , [ 7,  6,  5,  4] , [11, 10,  9,  8]])

>>> Code Explanation
# The array[:, ::-1] expression selects all rows (:) and reverses the order of elements in each row (::-1).

In [2]:
import numpy as np
A = np.arange(12, dtype='int').reshape(-1, 4)
transformed_array = A[:, ::-1]
print(transformed_array)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


2. The following  array is given:

array([[ 0,  1,  2,  3] , [ 4,  5,  6,  7] , [ 8,  9, 10, 11]])

Using the slice operator, transform this array into the following:

array([[11, 10,  9,  8] , [ 7,  6,  5,  4] , [ 3,  2,  1,  0]])

In [3]:
import numpy as np
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


3. Random seed is set to 42. The following array is given:

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

Extract the first channel (index 0) of this image array and print it to the console.

Expected output:

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]

In [5]:
import numpy as np
np.random.seed(42)
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
first_channel = image[:, :, 0]
print(first_channel)

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]


4. The following array is given:

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

Extract any array of shape (5, 5, 3) from this array and assign to the result variable.

In [6]:
import numpy as np
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
result = image[:5, :5, :]
print(result)

[[[129 219  27]
  [ 59  83 229]
  [ 41 175  91]
  [216 179  61]
  [110 213 173]]

 [[195 126   7]
  [ 67  76 213]
  [174 175 205]
  [  8  34 160]
  [ 97  44 205]]

 [[103  15 155]
  [169 131  93]
  [ 95 193   1]
  [ 76 204  79]
  [253   3 215]]

 [[ 84 145  53]
  [159  82  47]
  [220  37   4]
  [  8 190 178]
  [ 54 248 145]]

 [[201 144  40]
  [101 189 103]
  [ 19 229 227]
  [131  57 237]
  [ 13 249  15]]]
