1. np.full_like() :- If you want to create an array of the same shape and data type as the given array A filled with a specific value, you can use the np.full_like() function. Here's the corrected code:
>>>
import numpy as np
A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])
zeros_array = np.full_like(A, 0.0)
print(zeros_array)
>>> Output :- [[0. 0. 0.] [0. 0. 0.] [0. 0. 0.]]

2. The np.tri() function in NumPy can be used to create a two-dimensional array with ones at and below the main diagonal, and zeros elsewhere. Here's an example:
>>>
import numpy as np
n = 5  # Size of the array
triangular_array = np.tri(n)
print(triangular_array)
>>> Output :- 
    [[1. 0. 0. 0. 0.]
    [1. 1. 0. 0. 0.]
    [1. 1. 1. 0. 0.]
    [1. 1. 1. 1. 0.]
    [1. 1. 1. 1. 1.]]

3. The np.random.randint() function in NumPy is used to generate random integers from a specified range. Here's an example:
>>>
import numpy as np
# Generate a random integer between 0 and 9
random_integer = np.random.randint(10)
print(random_integer)
>>> Output :- 7

>>>
import numpy as np
# Generate a random integer between 1 and 100
random_integer = np.random.randint(low=1, high=101)
print(random_integer)
>>> Output :-  42

>>>
import numpy as np
# Generate a 1D array of 5 random integers between 0 and 9
random_array = np.random.randint(10, size=5)
print(random_array)
>>> Output :- [1 7 3 8 2]

1. The following array is given:

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])

Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.

In [1]:
import numpy as np
A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])
print(np.full_like(A , 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


2. Using Numpy create a two-dimensional array (lower triangular matrix):

array([[1., 0., 0., 0., 0.] , [1., 1., 0., 0., 0.] , [1., 1., 1., 0., 0.] , [1., 1., 1., 1., 0.] , [1., 1., 1., 1., 1.]])

In response, print result to the console.

In [3]:
import numpy as np
A = np.array([[1., 0., 0., 0., 0.] , [1., 1., 0., 0., 0.] , [1., 1., 1., 0., 0.] , [1., 1., 1., 1., 0.] , [1., 1., 1., 1., 1.]])
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


3. Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.
Example:

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]
 
 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]

In [4]:
import numpy as np
A = np.random.randint(0, 10, size=(2, 3, 4))
print(A)

[[[2 5 8 1]
  [3 3 3 4]
  [3 5 5 3]]

 [[3 2 5 0]
  [4 5 6 6]
  [9 2 3 4]]]


4. Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [5]:
import numpy as np
image = np.random.randint(0, 256, size=(200, 300), dtype=np.uint8)
print(image)

[[  3  85   1 ... 202  20 161]
 [  4  73 133 ... 240  14 106]
 [105 141  56 ...  45 240 129]
 ...
 [ 40   1  12 ... 121 225 134]
 [ 21  12 128 ... 219  36  78]
 [189  63 196 ... 161 227  37]]
