1. np.sort() is a NumPy function that returns a sorted copy of an array. By default, it sorts the array along the last axis.
Here's an example of using np.sort() on a one-dimensional array:
>>>
import numpy as np
arr = np.array([5, 2, 8, 1, 3])
sorted_arr = np.sort(arr)
print(sorted_arr)
>>> Output :- [1 2 3 5 8]
You can also use np.sort() on multi-dimensional arrays. By default, it sorts the values along the last axis. If you want to sort the array along a different axis or in a specific order, you can specify the axis and kind parameters.
# with kind parameter we can give the type of the sorting order of the array (Example :-MergeSort)
For example, to sort a two-dimensional array column-wise, you can specify axis=0:
>>>
import numpy as np
arr = np.array([[5, 3, 9] , [2, 1, 8]])
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)
>>> Output :- [[2 1 8] [5 3 9]]
# In this example, np.sort() is used to sort the two-dimensional array arr along axis=0, which corresponds to sorting the columns. The resulting sorted array is printed to the console.

2. np.expand_dims() is a function in NumPy that allows you to expand the dimensions of an array by inserting new axes. This can be useful when you want to reshape or manipulate arrays to perform certain operations.
The syntax of np.expand_dims() is as follows:
>>>
import numpy as np
arr = np.array([1, 2, 3])
expanded_arr = np.expand_dims(arr, axis=0)
print(expanded_arr)
print(expanded_arr.shape)
>>> Output :- 
    [[1 2 3]]
    (1, 3)
# NOTE >>>
In NumPy, the axis parameter specifies the axis along which a new dimension should be inserted when using the np.expand_dims() function.

In the context of np.expand_dims(), axis=0 means that a new dimension will be added at the beginning of the array. This results in the shape of the array being modified by inserting a new dimension of size 1 at the specified axis.

For example, if you have a 2-dimensional array A with shape (2, 3), and you apply np.expand_dims(A, axis=0), the resulting array will have shape (1, 2, 3). The original rows of A will become the rows of the expanded array, and the new dimension of size 1 will be added at the beginning.

Similarly, if you were to use axis=1 with np.expand_dims(), a new dimension would be inserted between the existing columns of the array.

In summary, the axis parameter determines the position along which the new dimension will be inserted when expanding an array using np.expand_dims().

1. The following array is given:

image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)

Sort this array along the rows in ascending order and assign to the variable image_sorted.

In [1]:
import numpy as np
image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
image_sorted = np.sort(image)
print(image_sorted)

[[  0   0   1 ... 253 254 255]
 [  0   0   2 ... 253 254 255]
 [  1   2   3 ... 254 255 255]
 ...
 [  1   2   2 ... 253 255 255]
 [  2   2   2 ... 252 252 255]
 [  0   1   4 ... 254 255 255]]


2. The following array is given:

A = np.array([[4, 2, 1] , [6, 4, 2]])

Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).
In response, print array to the console.
Expected output:

    [[[4 2 1]
     [6 4 2]]] 

In [2]:
import numpy as np
A = np.array([[4, 2, 1] , [6, 4, 2]])
print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


3. Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.
In response, print array to the console.

In [3]:
import numpy as np
np.random.seed(42)
image = np.random.randint(0, 256, size=(200, 300, 3), dtype=np.uint8)
print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


4. The following array is given:

image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

In [4]:
import numpy as np
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image_extended = np.expand_dims(image, axis=0)
print(image_extended)

[[[[145  30 244]
   [107   6 122]
   [201  42  86]
   ...
   [182 113 173]
   [140 196 105]
   [123  60 198]]

  [[221  40 190]
   [175  36 108]
   [ 33   0 106]
   ...
   [ 75 169  71]
   [218 180 159]
   [ 88  16   4]]

  [[141 115 148]
   [211  17 146]
   [118 201  37]
   ...
   [ 10 168 141]
   [136 119 180]
   [134 202  48]]

  ...

  [[105 148  18]
   [178 143 146]
   [249 136  32]
   ...
   [ 80  45 210]
   [182 138  93]
   [ 93 176 230]]

  [[  8  92  85]
   [105 188  47]
   [188 219 100]
   ...
   [117 202 126]
   [171 254  58]
   [ 60 227 231]]

  [[ 90  77 134]
   [121 220 235]
   [ 64 117 152]
   ...
   [ 60 122  47]
   [110 218 233]
   [233  85  89]]]]
