1. The np.split() function in NumPy allows you to split an array into multiple subarrays along a specified axis. 
Here's an example of how you can use np.split():

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
subarrays = np.split(arr, 5)
for subarray in subarrays:
    print(subarray)
>>> Output 
    [1, 2]
    [3, 4]
    [5, 6]
    [7, 8]
    [9, 10]

2. The np.count_nonzero() function in NumPy is used to count the number of non-zero elements in an array.
Here's an example of how to use it:

import numpy as np
arr = np.array([0, 5, 0, 3, 7, 0, 1])
count = np.count_nonzero(arr)
print(count)
>>> Output 4

3. The np.set_printoptions() function in NumPy is used to customize the printing behavior of NumPy arrays. It allows you to control various aspects such as the precision of floating-point numbers, the number of digits to display, the formatting of arrays, and more. 
Here's an example of how to use it:

import numpy as np
# Create a simple array
arr = np.array([0.123456789, 1.23456789, 12.3456789])
# Set the print options to display only 2 decimal places
np.set_printoptions(precision=2)
# Print the array
print(arr)
>>> Output [ 0.12  1.23 12.35]

1. The following two-dimensional array is given:

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

Split this array into three parts:

the first two columns assign to the A1 variable
the next four columns assign to the A2 variable
the last two columns assign to the A3 variable

In [1]:
import numpy as np

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A1, A2, A3 = np.split(A, [2, 6], axis=1)

print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 6 3 5]
 [2 3 6 1]
 [1 1 6 4]
 [6 1 2 3]
 [5 0 1 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


2. The following array is given:

A = np.random.randint(low=0, high=2, size=(10, 6))

Calculate the total number of non-zero elements in this array and print it to the console.

In [3]:
import numpy as np
np.random.seed(42)
A = np.random.randint(low=0, high=2, size=(10, 6))
print(np.count_nonzero(A))

31


3. The following array is given below:

A = np.random.randn(10, 4)

array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])

Set the Numpy option to print arrays with specified precision. Set precision to 4 and print this array.

In [8]:
import numpy as np

np.random.seed(42)
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)

print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


4. The following array is given:

A = np.array([1.2e-6, 1.7e-7])

Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation and print this array to the console.

In [ ]:
import numpy as np

A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)

print(A)