1. np.concatenate(), not np.concatinate(). The np.concatenate() function is used to concatenate arrays along a specified axis.

>>> Example
import numpy as np
# Create two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Concatenate along the row axis (axis=0)
result = np.concatenate((a, b), axis=0)
print(result)
>>> OUTPUT :- 
    [[1 2]
    [3 4]
    [5 6]
    [7 8]]

2. The np.column_stack() function is used to stack arrays horizontally, column-wise. It takes a sequence of 1-D or 2-D arrays as input and returns a 2-D array where the input arrays are stacked horizontally.

>>> Example
import numpy as np
# Create two 1-D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Stack the arrays horizontally
result = np.column_stack((a, b))
print(result)
>>> OUTPUT :- 
    [[1 4]
    [2 5]
    [3 6]]

1. The following arrays are given:

A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

Concatenate these arrays as follows:

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

In [2]:
import numpy as np
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
print(np.concatenate((A,B) , axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


2. The following arrays are given:

data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

Concatenate these arrays into one as shown below:

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

In [10]:
import numpy as np

data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

print(np.concatenate((data,target),axis=1))
# print(np.column_stack((data, target)))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


3. The following three one-dimensional arrays are given:

feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

Transform each of these arrays into a column and concatenate them into one array as shown below. In response, print this array to the console.

Expected result:

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]] 

In [15]:
import numpy as np
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
print(np.column_stack((feature1, feature2, feature3)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]
