#  Day 19 - np.divide(), np.multiply() & np.sqrt()

1. np.divide() is a NumPy function that performs element-wise division between two arrays. It returns an array with the same shape as the input arrays, where each element is the result of dividing the corresponding elements from the input arrays.
The syntax of np.divide() is as follows:
>            np.divide(x1, x2, out=None)
Here, x1 and x2 are the input arrays, and out is an optional parameter that specifies the output array where the result will be stored. If out is not provided, a new array will be created to store the result.
Here's an example that demonstrates the usage of np.divide():

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.divide(a, b)
print(result)
>>> Output : [0.25 0.4  0.5 ]

2. np.multiply() is a NumPy function that performs element-wise multiplication between two arrays. It returns an array with the same shape as the input arrays, where each element is the product of the corresponding elements from the input arrays.
The syntax of np.multiply() is as follows:
>           np.multiply(x1, x2, out=None)
Here, x1 and x2 are the input arrays, and out is an optional parameter that specifies the output array where the result will be stored. If out is not provided, a new array will be created to store the result.
Here's an example that demonstrates the usage of np.multiply():

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.multiply(a, b)
print(result)
>>> Output : [ 4 10 18]

3. np.sqrt() is a NumPy function that computes the element-wise square root of an array. It returns a new array with the same shape as the input array, where each element is the square root of the corresponding element in the input.
The syntax of np.sqrt() is as follows:
>           np.sqrt(x, out=None)
Here, x is the input array, and out is an optional parameter that specifies the output array where the result will be stored. If out is not provided, a new array will be created to store the result.
Here's an example that demonstrates the usage of np.sqrt():

import numpy as np
a = np.array([4, 9, 16])
result = np.sqrt(a)
print(result)
>>>Output : [2. 3. 4.]

1. The following arrays are given:

A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

Calculate arithmetic means of these arrays (elementwise) and print result to the console.

In [1]:
import numpy as np
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
means = np.mean([A, B], axis=0)
print(means)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


2. The following arrays are given:

A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

Multiply these arrays (elementwise) and print result to the console.

In [2]:
import numpy as np
A = np.array([[3, 4, 9, 2] , [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5] , [6, 3, 1, 6]])
print(np.multiply(A,B))

[[12 12 18 10]
 [30  9  2 30]]


3. The following array is given:

A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

Calculate the square root of each element of this array and print result to the console.

In [4]:
import numpy as np
A = np.array([[3, 4, 9, 2] , [5, 3, 2, 5]])
result = np.sqrt(A)
print(result)

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]
