1. np.where() is a function in NumPy that returns indices where a given condition is true. It can be used to locate elements in an array that satisfy a certain condition.
Here's an example that demonstrates how to use np.where() to extract elements from an array that are greater than 8:

import numpy as np
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])
indices = np.where(A > 8)
result = A[indices]
print(result)
>>>  [ 9.99  9.99 14.99]

2. np.ravel() is a function in NumPy that returns a flattened array by concatenating all elements of a given input array. The resulting array has a one-dimensional structure, with elements taken row-wise from the input array.
Here's an example that demonstrates how to use np.ravel():

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.ravel(A)
print(result)
>>> [1 2 3 4 5 6 7 8 9]

3. np.zeros_like() is a function in NumPy that creates an array of zeros with the same shape and data type as a specified input array.
Here's an example that demonstrates how to use np.zeros_like():

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
result = np.zeros_like(A)
print(result)
>>> [[0 0 0] [0 0 0]]

The following array is given:

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])

Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.

In [2]:
import numpy as np
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 14.99], [14.99, 2.39, 7.29]])
fixed_value = 10.0
result = np.where(A > 10, fixed_value, A)
print(result)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


2. Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])

In [3]:
import numpy as np
A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


3. The following array is given:

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])

Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.

In [4]:
import numpy as np
A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 14.99] , [14.99, 2.39, 7.29]])
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
