# Day 22 - np.random.shuffle(), np.argsort(), np.round() & np.roots()

1. np.random.shuffle() is a function from the NumPy library that shuffles the elements of an array in place. It modifies the original array by rearranging its elements randomly.
Here's an example usage of np.random.shuffle():

import numpy as np
# Create an array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
# Shuffle the array
np.random.shuffle(arr)
print("Shuffled array:", arr)
> Output :-
    Original array: [1 2 3 4 5]
    Shuffled array: [3 5 4 1 2]

2. np.argsort() is a function from the NumPy library that returns the indices that would sort an array in ascending order. It provides a sorted version of the array's indices instead of the actual sorted array.
Here's an example usage of np.argsort():

import numpy as np
# Create an array
arr = np.array([3, 1, 5, 2, 4])
# Get the sorted indices
sorted_indices = np.argsort(arr)
print("Sorted indices:", sorted_indices)
> Output :-    Sorted indices: [1 3 0 4 2]
The output shows the indices that would sort the array arr in ascending order. In this case, the smallest element is at index 1, followed by index 3, index 0, index 4, and index 2.
You can also use the sorted indices to retrieve the sorted array itself. Here's an example:
>>>
sorted_arr = arr[sorted_indices]
print("Sorted array:", sorted_arr)
> Output :-    Sorted array: [1 2 3 4 5]

3. np.round() is a function from the NumPy library that returns an array with each element rounded to the specified number of decimals. It allows you to round the values of an array to a desired precision.
Here's an example usage of np.round():

import numpy as np
# Create an array with floating-point values
arr = np.array([1.234, 2.567, 3.891, 4.123])
# Round the array elements to 2 decimals
rounded_arr = np.round(arr, decimals=2)
print("Original array:", arr)
print("Rounded array:", rounded_arr)
> Output :-
    Original array: [1.234 2.567 3.891 4.123]
    Rounded array: [1.23 2.57 3.89 4.12]

In the example, the np.round() function is used to round each element of the arr array to 2 decimal places. The resulting rounded values are stored in the rounded_arr array.
The decimals parameter specifies the number of decimal places to which the elements will be rounded. If decimals is not provided, it defaults to 0, resulting in rounding to the nearest integer.
Note that np.round() uses "round half to even" rounding strategy, also known as "banker's rounding", which means that when a value is exactly halfway between two possible rounded values, it rounds to the nearest even value.

4. np.roots() is a function from the NumPy library that calculates the roots of a polynomial with given coefficients. It returns an array containing the roots of the polynomial equation.
Here's an example usage of np.roots():

import numpy as np
# Coefficients of the polynomial equation: x^3 - 6x^2 + 11x - 6
coefficients = [1, -6, 11, -6]
# Calculate the roots of the polynomial equation
roots = np.roots(coefficients)
print("Roots:", roots)
> Output :-    Roots: [1. 2. 3.]

In the example, np.roots() is used to find the roots of the polynomial equation with coefficients [1, -6, 11, -6]. The resulting roots are stored in the roots array.
The input to np.roots() is a 1-D array containing the coefficients of the polynomial in decreasing order of powers. The function then solves the polynomial equation and returns the complex or real roots depending on the coefficients.
Note that if the polynomial equation has complex roots, they will be returned as complex numbers.

1. The following array is given:

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

Starting with the second row of this array, randomly shuffle the rows and print result to the console.

In [5]:
import numpy as np
 
 
np.random.seed(42)
 
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
 
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]


2. The following array is given:

A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

Return a list of indexes that sorts this array in ascending order and print it to the console.

In [6]:
import numpy as np
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
print(np.argsort(A))

[5 2 1 0 4 3]


3. The following array is given:

A = np.random.randn(10, 8)

Round the values of this array to three decimal places and print result to the console.

In [7]:
import numpy as np
np.random.seed(42)
A = np.random.randn(10, 8)
rounded_arr = np.round(A, decimals=3)
print(rounded_arr)

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


4. Calculate  the roots of the following polynomial:

w(x) = 4x^2 + 5x + 1

In response, print these roots to the console.

In [9]:
import numpy as np
coefficients = [4,5,1]
roots = np.roots(coefficients)
print(roots)

IndentationError: unexpected indent (252993553.py, line 4)