# np.char.strip(), np.char.replace() & np.char.count()

1. The np.char.strip() function in NumPy is used to remove leading and trailing whitespaces (or other specified characters) from the elements of a character array.

import numpy as np
A = np.array(['  Hello  ', '  Welcome  ', '  to  ', '  Python  '])
result = np.char.strip(A)
print(result)
> Output :-
    ['Hello' 'Welcome' 'to' 'Python']
In this example, the np.char.strip() function removes leading and trailing whitespaces from each element of array A. The resulting array contains the stripped strings.
You can also specify the characters to be stripped using the chars parameter. For example, np.char.strip(A, 'x') will remove leading and trailing 'x' characters from the elements of array A.

2. The np.char.replace() function in NumPy is used to replace specified substrings or characters in a character array with another substring or character.

import numpy as np
A = np.array(['Hello', 'World', 'Hello', 'Python'])
result = np.char.replace(A, 'Hello', 'Hi')
print(result)
> Output :-
    ['Hi' 'World' 'Hi' 'Python']

3. The np.char.count() function in NumPy is used to count the occurrences of a substring or character in a character array.

import numpy as np
A = np.array(['apple', 'banana', 'orange', 'pineapple'])
count = np.char.count(A, 'a')
print(count)
> Output :-
    [1 3 1 1]

1. The following array is given:

A = np.array([['#summer#time#mood'],
              ['#sport#time']])

Replace all # characters with spaces and then strip all unnecessary white characters around the text as shown below. In response, print this array to the console.

Expected result:

    [['summer time mood']
    ['sport time']]

In [1]:
import numpy as np

A = np.array([['#summer#time#mood'],
              ['#sport#time']])

print(np.char.strip(np.char.replace(A, '#', ' ')))

[['summer time mood']
 ['sport time']]


2. The following array is given:

A = np.array(
    [
        ['#summer#time#mood', '#vibe'],
        ['#sport#time', '#good#time'],
        ['#event#summer', '#fast#move'],
    ]
)

Count the number of occurrences of the word 'time' in each element of this array.

Expected result:

[[1 0]
 [1 1]
 [0 0]]

In [2]:
import numpy as np
 
A = np.array(
    [
        ['#summer#time#mood', '#vibe'],
        ['#sport#time', '#good#time'],
        ['#event#summer', '#fast#move'],
    ]
)
 
print(np.char.count(A, 'time'))

[[1 0]
 [1 1]
 [0 0]]


3. The following text is given:

text = """ALIOR    PLALIOR00045    88 860 000    1 386 216 000    0,891    2,16    14
CCC    PLCCC0000016    27 918 000    1 292 603 400    0,831    5,28    42
CDPROJEKT    PLOPTTC00011    67 348 000    22 864 646 000    14,702    7,39    7
CYFRPLSAT    PLCFRPT00013    275 301 000    6 854 994 900    4,408    1,17    14
DINOPL    PLDINPL00011    47 937 000    8 916 282 000    5,733    9,13    12
JSW    PLJSW0000015    52 636 000    716 902 320    0,461    1,51    24
KGHM    PLKGHM000017    136 410 000    9 881 540 400    6,354    4,78    8
LOTOS    PLLOTOS00025    86 543 000    5 609 717 260    3,607    2,91    16
LPP    PLLPP0000011    1 306 000    7 444 200 000    4,787    1,43    19
MBANK    PLBRE0000012    12 997 000    2 830 746 600    1,820    0,42    24
ORANGEPL    PLTLKPL00017    647 357 000    4 285 503 340    2,756    1,16    13
PEKAO    PLPEKAO00016    176 379 000    9 619 710 660    6,185    5,27    9
PGE    PLPGER000010    796 776 000    3 561 588 720    2,290    2,88    18
PGNIG    PLPGNIG00014    1 624 608 000    6 072 784 704    3,905    1,56    12
PKNORLEN    PLPKN0000018    289 049 000    17 701 360 760    11,382    12,44    8
PKOBP    PLPKO0000016    857 593 000    18 807 014 490    12,093    10,49    9
PLAY    LU1642887738    114 151 000    3 696 209 380    2,377    1,47    16
PZU    PLPZU0000011    568 305 000    17 515 160 100    11,262    6,64    6
SANPL    PLBZ00000044    33 207 000    5 213 499 000    3,352    1,91    18
TAURONPE    PLTAURN00011    1 043 590 000    1 252 308 000    0,805    1,21    33"""


Columns mean:

Instrument | ISIN code | Package | Package (PLN) | Share in portfolio (%) | Share in trading shares and PDAs per session (%) | Average spread per session

Split text into lines. Then split each line by the tab character \t and create an array (without headers) containing the following data as shown below. Assign this array to the result variable and print it to the console.


Expected result:

[['ALIOR' 'PLALIOR00045' '88 860 000' '1 386 216 000' '0,891' '2,16' '14']
 ['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0,831' '5,28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14,702' '7,39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4,408' '1,17' '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5,733' '9,13' '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0,461' '1,51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6,354' '4,78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3,607' '2,91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4,787' '1,43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1,820' '0,42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2,756' '1,16' '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6,185' '5,27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2,290' '2,88' '18']
 ['PGNIG' 'PLPGNIG00014' '1 624 608 000' '6 072 784 704' '3,905' '1,56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289 049 000' '17 701 360 760' '11,382' '12,44' '8']
 ['PKOBP' 'PLPKO0000016' '857 593 000' '18 807 014 490' '12,093' '10,49' '9']
 ['PLAY' 'LU1642887738' '114 151 000' '3 696 209 380' '2,377' '1,47' '16']
 ['PZU' 'PLPZU0000011' '568 305 000' '17 515 160 100' '11,262' '6,64' '6']
 ['SANPL' 'PLBZ00000044' '33 207 000' '5 213 499 000' '3,352' '1,91' '18']
 ['TAURONPE' 'PLTAURN00011' '1 043 590 000' '1 252 308 000' '0,805' '1,21' '33']]

In [4]:
import numpy as np
 
 
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
 
lines = text.splitlines()
lines = [line.split('\t') for line in lines]
result = np.array(lines, dtype=str)
print(result)

[['ALIOR' 'PLALIOR00045' '88 860 000' '1 386 216 000' '0,891' '2,16' '14']
 ['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0,831' '5,28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14,702'
  '7,39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4,408' '1,17'
  '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5,733' '9,13'
  '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0,461' '1,51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6,354' '4,78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3,607' '2,91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4,787' '1,43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1,820' '0,42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2,756' '1,16'
  '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6,185' '5,27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2,290' '2,88' '18']
 ['PGNIG' 'PL