# Day 23 - np.polyadd() & np.sign()

1. Calculate the roots of the following polynomials:

Q(X) = 2X^3 + 4X^2 - 5X + 1
R(x) = 2X^3 - 5X + 1

In response print these roots to the console

In [1]:
import numpy as np
 
 
Q = np.array([2, 4, -5, 1])
R = np.array([2, 0, -5, 1])
 
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


2. The following polynomials are given:

Q(X) = 4X^2 + 5X + 1
R(x) = 2X^3 + 4X^2 - 5X + 1

Perform the following operations and print results to the console as shown below:

Q(X) + R(x)
Q(X) - R(x)
Q(X) * R(x)
Q(X) + 2*R(x)

In [2]:
import numpy as np
 
 
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


3. The following array is given:

A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

Use the sign function for this array.

Reminder: The sign function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values

In [3]:
import numpy as np


A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
              
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]
