1. # Day 20 - np.allclose(), np.dot() & np.linalg.det()

np.allclose() is a NumPy function that compares whether two arrays are element-wise equal within a specified tolerance. It returns True if all elements in the arrays are close (within the specified tolerance) and False otherwise.
Here's the syntax of np.allclose():
>    np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
a and b are the arrays to compare.
rtol (optional) is the relative tolerance (default is 1e-05).
atol (optional) is the absolute tolerance (default is 1e-08).
equal_nan (optional) determines whether NaN values are considered equal (default is False).
The function returns True if the arrays are element-wise equal within the specified tolerance and False otherwise.import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.000001, 2.000002, 2.999999])
result = np.allclose(a, b)
print(result)  # Output: True

2. np.dot() is a NumPy function used for matrix multiplication or dot product calculation. It computes the dot product between two arrays.
There are *two ways* to use np.dot():
Multiply two arrays element-wise (for 1-D arrays, it calculates the inner product):
>       np.dot(a, b)
Perform matrix multiplication between two 2-D arrays:
>       np.dot(a, b)
Here's an example to illustrate each usage:
    Element-wise multiplication (dot product of 1-D arrays):

    import numpy as np
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    result = np.dot(a, b)
    print(result)  # Output: 32
In this example, np.dot(a, b) calculates the dot product between arrays a and b, resulting in the scalar value 32.
Matrix multiplication (dot product of 2-D arrays):

import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print(result)
# Output:
# [[19 22]
#  [43 50]]

3. np.linalg.det() is a NumPy function that calculates the determinant of a square matrix. The determinant is a scalar value that represents certain properties of the matrix.
The syntax for using np.linalg.det() is:
>   np.linalg.det(a)
where a is the input square matrix.
Here's an example to illustrate the usage of np.linalg.det():
    import numpy as np
    a = np.array([[1, 2], [3, 4]])
    det = np.linalg.det(a) 
    print(det)  # Output: -2.0

1. The following arrays are given:

A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.

In response, print result to the console.

In [2]:
import numpy as np
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
result = np.sin(A)**2 + np.cos(A)**2
print(np.allclose(result, B))

True


2. The following arrays are given:

A = np.array([[2, 3] , [-4, 2] , [5, 0]])
B = np.array([[4, 3, 2] , [-1, 0, 2]])

Shapes of these arrays:

A - 3x2

B - 2x3

Perform matrix multiplication A x B and print result to the console.

In [3]:
import numpy as np
A = np.array([[2, 3] , [-4, 2] , [5, 0]])
B = np.array([[4, 3, 2] , [-1, 0, 2]])
print(np.dot(A,B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


3. The following array (square matrix) is given:

A = np.array([[-2, 0, 4] , [5, 2, -1] , [-4, 2, 4]])

Calculate the determinant of this matrix and print it to the console.

In [4]:
import numpy as np
A = np.array([[-2, 0, 4] , [5, 2, -1] , [-4, 2, 4]])
print(np.linalg.det(A))

51.999999999999986
