# np.linalg.eig(), np.linalg.inv() & np.trace()

1. np.linalg.eig() in NumPy, which is used to compute the eigenvalues and eigenvectors of a square matrix.
Here's an example of how to use np.linalg.eig():

import numpy as np
A = np.array([[2, -1], [4, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)
> Output 
    Eigenvalues: [2.5+1.93649167j 2.5-1.93649167j]
    Eigenvectors:
    [[ 0.19611614+0.33106601j  0.19611614-0.33106601j]
    [ 0.58834841+0.j         -0.58834841-0.j        ]]

2. np.linalg.inv() in NumPy, which is used to compute the inverse of a square matrix.
Here's an example of how to use np.linalg.inv():

import numpy as np
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("Inverse of A:")
print(A_inv)

> Output
    Inverse of A:
    [[-2.   1. ]
    [ 1.5 -0.5]]

3. The np.trace() function in NumPy is used to calculate the sum of the diagonal elements of a square matrix. It returns the trace of the matrix.
Here's an example of how to use np.trace():

import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
trace_A = np.trace(A)
print("Trace of A:", trace_A)
> Output    Trace of A: 15

1. The following array (square matrix) is given:

A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])

Calculate eigenvalues and their corresponding eigenvectors of this matrix and print to the console

In [1]:
import numpy as np
A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


2. The following array (square matrix) is given:

A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])

Find the inverse matrix to this matrix and print it to the console.

In [2]:
import numpy as np
A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


3. The following array (square matrix) is given:

A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])

Find the trace of this matrix (sum of elements on the main diagonal) and print result to the console.

In [3]:
import numpy as np
A = np.array([[5, 8, 16] , [4, 1, 8] , [-4, 4, -11]])
print(np.trace(A))

-5


4. The following arrays are given:

A = np.array([[2, 0] , [4, 2] , [5, 3] , [4, 2]])

B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

Shapes of these arrays:

A - 4x2
B - 1x8

Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.

In [5]:
import numpy as np
A = np.array([[2, 0] , [4, 2] , [5, 3] , [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
print(np.dot(A, B.reshape(2, -1)))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]
