# Day 84 - linear regression & polynomial features

1. The following df DataFrame is given: <br>
<br>
   years  salary <br>
0      1    4000 <br>
1      2    4250 <br>
2      3    4500 <br>
3      4    4750 <br>
4      5    5000 <br>
5      6    5250 <br>
<br>
The first column describes the years of experience (feature variable), the second column describes the salary (target variable). <br>
Using the scikit-learn package and the LinearRegression class, find the linear regression equation for this problem.

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
 
df = pd.DataFrame(
    {
        'years': [1, 2, 3, 4, 5, 6],
        'salary': [4000, 4250, 4500, 4750, 5000, 5250],
    }
)
 
model = LinearRegression()
model.fit(df[['years']], df[['salary']])
 
print(
    f'Linear regression: {model.intercept_[0]:.2f} + '
    f'{model.coef_[0][0]:.2f}x'
)

Linear regression: 3750.00 + 250.00x


2. Load data.csv file into a DataFrame and assign to df variable. <br>
Then, based on the variable column, create a linear regression model that allows you to predict the values of the target column (create the model based on all available data). Use the scikit-learn package and the LinearRegression class. <br>
Evaluate the model using score() and print the result

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
 
df = pd.read_csv('data.csv')
data = df[['variable']]
target = df['target']
model = LinearRegression()
model.fit(data, target)
print(f'{model.score(data, target):.4f}')

0.5532


3. Load the data.csv file into the DataFrame. <br>
Then extract the polynomial features from the var1 column with degree = 2.

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
 
np.set_printoptions(suppress=True, precision=3)
df = pd.read_csv('data.csv')
poly = PolynomialFeatures(degree=2)
df_poly = poly.fit_transform(df)
print(df_poly)

[[    1.       -1.137   -13.153     1.292    14.95    172.999]
 [    1.       -1.419   -36.317     2.012    51.517  1318.899]
 [    1.        1.745   104.185     3.044   181.783 10854.481]
 [    1.       -0.232   -15.823     0.054     3.674   250.36 ]
 [    1.       -0.489   -24.082     0.239    11.784   579.919]
 [    1.        0.289    41.157     0.084    11.898  1693.865]
 [    1.        1.332   101.416     1.773   135.045 10285.28 ]
 [    1.       -0.529   -24.058     0.28     12.734   578.764]
 [    1.        1.129     4.934     1.274     5.569    24.343]
 [    1.       -0.175    44.85      0.03     -7.831  2011.546]
 [    1.        1.028    -2.047     1.057    -2.105     4.19 ]
 [    1.       -0.939    21.001     0.883   -19.729   441.048]
 [    1.        0.66    -32.98      0.436   -21.775  1087.709]
 [    1.        0.245    -1.358     0.06     -0.332     1.845]
 [    1.       -0.698   -27.181     0.487    18.967   738.831]
 [    1.        0.989    63.35      0.978    62.658  40