# Day 87 - accuracy, confusion matrix & decision tree

1. The predictions.csv file contains the predictions based on the certain multi-class classification model (3 classes). The y_true column describes the actual values, and the y_pred column describes the values predicted by the model. <br>
Using the accuracy_score() function from the scikit-learn package, calculate the accuracy of this model.

In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
 
predictions = pd.read_csv('predictions(87).csv')
acc = accuracy_score(predictions['y_true'], predictions['y_pred'])
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.7241


2. The predictions.csv file contains predictions based on the certain multi-class classification model (3 classes). The y_true column describes the actual values, and the y_pred column describes the values predicted by the model.
Use the confusion_matrix() function from the scikit-learn package to calculate the confusion matrix and print it to the console.

In [4]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
 
predictions = pd.read_csv('predictions(87).csv')
cm = confusion_matrix(predictions['y_true'], predictions['y_pred'])
print(cm)

[[ 6  1  0]
 [ 3 10  2]
 [ 0  2  5]]


3. The following arrays are given: <br>
<br>
X_train, y_train <br>
X_test, y_test <br>
<br>
Using the DecisionTreeClassifier class from the scikit-learn package, create classification model (leave the default arguments). Train the model on the train set and evaluate on the test set. <br>
In response, print the model accuracy (up to four decimal places) to the console as shown below.

In [5]:
import numpy as np
import pandas as pd
 
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
 
np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]
 
X_train, X_test, y_train, y_test = train_test_split(data, target)
 
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
acc = classifier.score(X_test, y_test)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9020
