# Day 86 - StandardScaler & entropy

1. Load the data.csv file into the DataFrame. <br>
Then, using the StandardScaler class from the scikit-learn package, standardize all the variables.

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
 
np.set_printoptions(precision=4, suppress=True)
df = pd.read_csv('data.csv')
 
scaler = StandardScaler()
scaler.fit(df)
 
df_scaled = scaler.transform(df)
print(df_scaled)

[[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
 [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
 [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
 [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
 [-0.7449 -1.1397 -0.7236 -0.745   0.0771]
 [ 1.8496  2.1747  1.9719  1.8048  1.3537]
 [ 2.2534  0.5208  2.2644  2.4466  0.5363]
 [ 0.9819 -1.0039  0.9382  0.8882 -0.0203]
 [-0.2294 -0.8236 -0.236  -0.3987  0.6429]
 [-0.069  -0.6544 -0.1338 -0.1639 -2.1663]
 [-0.2666  1.2665 -0.3344 -0.3457 -0.7709]
 [ 0.7557 -0.1692  0.7035  0.6847 -0.7183]
 [ 0.2374  0.0445  0.1351  0.1047 -1.0339]
 [ 0.6068  0.5164  0.6293  0.5087  1.2613]
 [-0.5158 -1.6227 -0.5469 -0.551  -0.6202]
 [ 1.4201  1.498   1.5189  1.4114  1.6167]
 [ 0.1916 -1.0818  0.1005  0.0766 -0.9977]
 [-1.14    0.0066 -1.1321 -1.0148  0.1098]
 [-2.0504 -1.3645 -1.9945 -1.5123  1.2968]
 [ 1.8353  0.2893  1.8772  1.932   0.4154]
 [-0.0977 -0.8392 -0.0737 -0.2091  0.1382]
 [-0.5845 -0.4096 -0.5827 -0.617   0.2946]
 [ 2.1388  0.6054  2.149   2.2248  1.2755]
 [-1.1773  

2. Load X_train.csv and X_test.csv files respectively to DataFrame named X_train and X_test. <br>
Then use the StandardScaler class from the scikit-learn package to standardize the data (fit the scaler on the X_train). <br>
In response, print the first five rows of X_train and X_test to the console.

In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
 
X_train = pd.read_csv('x_train.csv')
X_test = pd.read_csv('x_test.csv')
 
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
print(X_train[:5])
print(X_test[:5])

[[-0.3491 -1.4385 -0.4117 -0.3905 -1.8637]
 [-0.2047  0.3126 -0.1337 -0.2759  1.0781]
 [-0.3293 -0.2151 -0.3174 -0.3644 -1.5799]
 [ 1.0274  2.0898  1.0469  0.9176  0.3163]
 [ 1.829   0.696   1.7637  1.7838 -0.3337]]
[[-0.4681 -0.1417 -0.4447 -0.486   0.2934]
 [ 1.3645  0.4996  1.3064  1.3344 -0.3917]
 [ 0.3788  0.0665  0.4043  0.264   0.9777]
 [-0.4879 -0.3594 -0.429  -0.5256  0.7054]
 [-0.7315 -1.1261 -0.71   -0.7079  0.307 ]]


3. Implement the entropy() function using the numpy package. Round the result to four decimal places.<br>
<br>
Then the following df DataFrame is given:<br>

   val_1  val_2 <br>
0   0.01   0.99 <br>
1   0.11   0.89 <br>
2   0.21   0.79 <br>
3   0.31   0.69 <br>
4   0.41   0.59 <br>
5   0.51   0.49 <br>
6   0.61   0.39 <br>
7   0.71   0.29 <br>
8   0.81   0.19 <br>
9   0.91   0.09 <br>
<br>
Using the implemented function, calculate the entropy for each pair in this DataFrame and assign to the 'entropy' column.

In [6]:
import numpy as np
import pandas as pd
 
 
def entropy(x):
    return np.round(-np.sum(x * np.log2(x)), 4)
 
df = pd.DataFrame(
    {
        'val_1': np.arange(0.01, 1.0, 0.1),
        'val_2': 1 - np.arange(0.01, 1.0, 0.1),
    }
)
df['entropy'] = [
    entropy([row[1][0], row[1][1]]) for row in df.iterrows()
]
print(df)

   val_1  val_2  entropy
0   0.01   0.99   0.0808
1   0.11   0.89   0.4999
2   0.21   0.79   0.7415
3   0.31   0.69   0.8932
4   0.41   0.59   0.9765
5   0.51   0.49   0.9997
6   0.61   0.39   0.9648
7   0.71   0.29   0.8687
8   0.81   0.19   0.7015
9   0.91   0.09   0.4365
