1. np.zeros() is a NumPy function that creates an array filled with zeros. It takes the shape of the desired array as an argument and returns an array of that shape, where all elements are set to zero.
>>>>> arr = np.zeros("Give Dimension")

2. np.append() is a NumPy function that allows you to append values to an existing array. It takes the array to which you want to append values and the values themselves as arguments, and returns a new array with the appended values.

>>> It's same as python list
import numpy as np

# Create an initial array
arr = np.array([1, 2, 3])

# Append a single value to the array
new_arr1 = np.append(arr, 4)
print(new_arr1)
# Output: [1 2 3 4]

# Append multiple values to the array
new_arr2 = np.append(arr, [4, 5, 6])
print(new_arr2)
# Output: [1 2 3 4 5 6]

# Append values to a multi-dimensional array
arr2D = np.array([[1, 2], [3, 4]])
new_arr2D = np.append(arr2D, [[5, 6]], axis=0)
print(new_arr2D)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

3. np.intersect1d() is a NumPy function that returns the sorted, unique values that are in both of the input arrays. It computes the intersection of two arrays and returns the common elements.
>>>Here's an example usage of np.intersect1d() :
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

# Compute the intersection of the two arrays
intersection = np.intersect1d(arr1, arr2)
print(intersection)
# Output: [4 5]

1. The following array:

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

transform to the following:

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

In [1]:
import numpy as np

# Create the initial array
arr = np.zeros((6, 6), dtype=int)

# Assign values using the slice operator
arr[::2, ::2] = 10 # The arr[::2, ::2] selects every other row and column starting from the first (0th) row and column.
arr[1::2, ::2] = 5 # arr[1::2, ::2] selects every other row starting from the second (1st) row and every column starting from the first (0th) column.

print(arr)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


2. Combine the following arrays into one as shown below and print it to the console.

A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

In [2]:
import numpy as np

A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2] , [0, 5, 2, 6]])

print(np.append(A , B , axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


3. The following arrays are given:

A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3] , [2, 8, 0, 9]])      

Extract the same elements (intersection) of the arrays as a list and print result to the console.

In [3]:
import numpy as np

A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3] , [2, 8, 0, 9]])

print(np.intersect1d(A, B))

[0 2 3]
