1. np.unique() is a NumPy function that returns the sorted unique elements of an array. It takes an array as input and returns a new array with only the unique elements, removing any duplicates.
>>> Examples

import numpy as np
arr = np.array([2, 1, 3, 2, 4, 3, 1, 5])
unique_values = np.unique(arr)
print(unique_values)
> OutPut :- [1 2 3 4 5]

import numpy as np
arr = np.array([[1, 2, 3] , [2, 3, 4] , [3, 4, 5]])
unique_values = np.unique(arr)
print(unique_values)
> OutPut :- [1 2 3 4 5]

2. np.argmax() is a NumPy function that returns the indices of the maximum values along a specified axis of an array. It is used to find the indices of the maximum element(s) in an array.
>>> Examples

import numpy as np
arr = np.array([4, 2, 7, 1, 9, 5])
max_index = np.argmax(arr)
print(max_index)
> Output:- 4 (Index of 9 is 4)

import numpy as np
arr = np.array([[1, 2, 3] , [4, 5, 6] , [7, 8, 9]])
max_indices = np.argmax(arr, axis=1)
print(max_indices)
>Output :- [2 2 2]
    In this example, the np.argmax(arr, axis=1) call returns an array containing the indices of the maximum values along each row of the array arr. So, the maximum value in the first row is at index 2, the maximum value in the second row is at index 2, and the maximum value in the third row is also at index 2.

3. np.sort() is a NumPy function used to sort the elements of an array along a specified axis. It returns a sorted copy of the array, leaving the original array unchanged.
>>> Examples

import numpy as np
arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)
> OutPut :- [1 2 3 4 5]

import numpy as np
arr = np.array([[3, 1, 4] , [2, 5, 6]])
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)
> OutPut :- [[1 3 4] [2 5 6]]

1. The following array is given:

A = np.array([[5, 1, 2, 1, 2] , [9, 1, 9, 7, 5] , [4, 1, 5, 7, 9]])

Extract all unique values of this array as a list and print it to the console.

In [1]:
import numpy as np 
A = np.array([[5, 1, 2, 1, 2] , [9, 1, 9, 7, 5] , [4, 1, 5, 7, 9]])
print(np.unique(A))

[1 2 4 5 7 9]


2. The following array is given:

A = np.array([[0.4, 0.3, 0.3] , [0.1, 0.1, 0.8] , [0.2, 0.5, 0.3]])

Return a list of indexes with maximum values for each row from this array and print it to the console.

In [3]:
import numpy as np
A = np.array([[0.4, 0.3, 0.3] , [0.1, 0.1, 0.8] , [0.2, 0.5, 0.3]])
print(np.argmax(A , axis = 1))

[0 2 1]


3. The following array is given:

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 4.99] , [14.99, 2.39, 7.29]])

Sort this array:

by row (ascending)
by column (ascending)

And print result to the console as shown below.

In [6]:
import numpy as np
 
A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 4.99] , [14.99, 2.39, 7.29]])

print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


4. Extract all elements from the following array with a value greater than 8 and print result to the console.

A = np.array([[4.99, 3.49, 9.99] , [1.99, 9.99, 4.99] , [14.99, 2.39, 7.29]])

Expected result :- [ 9.99  9.99 14.99]

In [7]:
import numpy as np

A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])
result = A[A > 8]

print(result)

[ 9.99  9.99 14.99]
