ONE WEEK 🥲🥲🥲

1. The np.diag() function in NumPy is used to create a square matrix with the given input array as its diagonal, and all other elements set to zero. It can also extract the diagonal elements from a given matrix.
Here are a few examples to demonstrate the usage of np.diag() -->

import numpy as np
arr = np.array([1, 2, 3])  
diagonal_matrix = np.diag(arr)
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

diagonal_elements = np.diag(matrix)
print(diagonal_elements)

[1 5 9]

                                        ******************

2. The np.save() function in NumPy is used to save an array or multiple arrays to a binary file with the extension ".npy". This function allows you to store the array data in a format that can be easily loaded and used later.
Here's an example to demonstrate the usage of np.save() -->

import numpy as np
arr = np.array([1, 2, 3, 4, 5])  
np.save('array_data.npy', arr)

In this example, the np.save() function is used to save the array arr to a file named "array_data.npy". The file will be created in the current directory. The array data is stored in a binary format optimized for efficient loading and saving.
To load the saved array back into memory, you can use the np.load() function -->

loaded_arr = np.load('array_data.npy')
print(loaded_arr)

[1 2 3 4 5]

                                        ******************

3. The np.savetxt() and np.loadtxt() functions in NumPy are used to save and load arrays as text files, respectively.

np.savetxt(): This function is used to save an array to a text file. It offers flexible options for formatting and customization of the saved data.
Here's an example of using np.savetxt() to save a NumPy array as a text file -->

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('array_data.txt', arr, delimiter=',')

In this example, the np.savetxt() function saves the array arr to a text file named "array_data.txt". The delimiter=',' parameter specifies that the values in the file should be separated by commas. By default, the data is saved with a floating-point format.
The resulting "array_data.txt" file would contain the following contents -->

1.000000000000000000e+00, 2.000000000000000000e+00, 3.000000000000000000e+00
4.000000000000000000e+00, 5.000000000000000000e+00, 6.000000000000000000e+00

You can customize the format of the saved data using the fmt parameter of np.savetxt(). For example, to save the data as integers, you can use fmt='%d':

np.savetxt('array_data.txt', arr, delimiter=',', fmt='%d')
The resulting "array_data.txt" file would contain the following contents -->

1, 2, 3
4, 5, 6

np.loadtxt(): This function is used to load data from a text file into a NumPy array.
Here's an example of using np.loadtxt() to load data from a text file -->

import numpy as np
loaded_arr = np.loadtxt('array_data.txt', delimiter=',')
print(loaded_arr)

In this example, the np.loadtxt() function reads the contents of the "array_data.txt" file and returns the data as a NumPy array. The delimiter=',' parameter specifies that the values in the file are separated by commas.

[[1. 2. 3.] [4. 5. 6.]]
By default, np.loadtxt() assumes that the data in the file is in a floating-point format. If the data in the file is in a different format, you can specify the data type using the dtype parameter.

1. Using Numpy create the following two-dimensional array:
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]

In [2]:
import numpy as np

sanj = np.array([0,1,2,3,4,5])
san = np.diag(sanj)
print(san)

# or you can simply write it as --> print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


2. Using Numpy create the following array:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
import numpy as np
arr = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11]])
np.save('arr_data.npy' , arr)


loaded_arr = np.load('arr_data.npy')
print(loaded_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


3. Using Numpy create the following array:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.

In [6]:
import numpy as np

arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

np.savetxt('array.txt', arr, fmt='%.2f')

loaded_arr = np.loadtxt('array.txt')
print(loaded_arr)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
