1. 
The np.greater() function is a NumPy function that compares two arrays element-wise and returns a Boolean array of the same shape as the input arrays. It checks whether the elements in the first array are greater than the corresponding elements in the second array.

Here's the general syntax of np.greater(arr1 , arr2)

2. 
The np.zeros() function is a NumPy function that creates a new array filled with zeros. It allows you to specify the shape and data type of the array you want to create.

Here's the general syntax of np.zeros() -->  np.zeros(shape, dtype=float, order='C')

shape: The shape of the array to be created. It can be specified as a single integer or as a tuple of integers.
dtype (optional): The data type of the elements in the array. The default is float.
order (optional): The memory layout of the array. It can be 'C' for row-major (C-style) or 'F' for column-major (Fortran-style). The default is 'C'.

3. 
The np.ones() function is a NumPy function that creates a new array filled with ones. It allows you to specify the shape and data type of the array you want to create.

Here's the general syntax of np.ones() --> np.ones(shape, dtype=float, order='C')

4. `
The np.full() function is a NumPy function that creates a new array with a specified shape and fill value. It allows you to create an array of any shape and fill it with a specific value.

Here's the general syntax of np.full() --> np.full(shape, fill_value, dtype=None, order='C')

1. Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

Expected result :  [ True False False False]

In [1]:
import numpy as np

A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(np.greater(A,B))

[ True False False False]


2. Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.

In [2]:
import numpy as np

print(np.zeros((4,4) , dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


3. Using Numpy, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.

In [4]:
# with np.ones() method
import numpy as np

print(np.ones(shape=(10,10) , dtype=float )* 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [3]:
# with np.full() method
import numpy as np

print(np.full(shape=(10, 10), fill_value=255, dtype='float'))


[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
