1. The np.reshape() function in NumPy is used to change the shape of an array while maintaining the same elements. It allows you to reshape an array into a new shape without modifying the original data.
The syntax of np.reshape() is as follows -->

np.reshape(array, new_shape)

                            *************************

2.  you can convert a NumPy array to a Python list using the tolist() method of the NumPy array object. The tolist() method returns a Python list containing the elements of the array.
Here's an example -->

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
list_arr = arr.tolist()

print(list_arr)

OUTPUT :- [1, 2, 3, 4, 5]

                            *************************

3. The np.pad() function in NumPy is used to pad an array with values along specified dimensions. It allows you to add values to the edges of an array, effectively increasing its size.

The np.pad() function takes several arguments:

array: The input array to be padded.
pad_width: The number of values to pad on each axis. It can be a single integer or a tuple of integers specifying the padding for each dimension.
mode: The padding mode. It determines how the values are padded. Some common modes include "constant", "edge", "reflect", and "wrap".
constant_values: The value to use for padding if the mode is set to "constant".
Here's an example usage of np.pad() -->

import numpy as np

arr = np.array([[1, 2], [3, 4]])
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(padded_arr)

OUTPUT :- 
[[0 0 0]
 [0 1 2]
 [0 3 4]
 [0 0 0]]

1. Using Numpy create and convert the following array into the list:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In response, print list to the console.

In [4]:
import numpy as np

arr = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

listed_arr = arr.tolist()

print(listed_arr)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


2. The following array is given:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Using the slice operator, transform this array into the following:
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In response, print transformed array to the console.

In [6]:
import numpy as np

arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

transformed_arr = arr[::-1]

print(transformed_arr)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


3. The following array:
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

transform to this array:
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
import numpy as np

arr = np.ones((4, 4))
transformed_arr = np.pad(arr, ((1, 1), (1, 1)), mode='constant')

print(transformed_arr)

'''
    Explanation
    In this code, we first create a 4x4 array of ones using np.ones((4, 4)). Then, we use np.pad to add a border of zeros around the array. The ((1, 1), (1, 1)) parameter specifies the amount of padding to add on each side of the array. The mode='constant' parameter ensures that zeros are used for padding. The resulting array transformed_arr has the desired transformation, where the original array is padded with zeros on all sides.
'''

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


"\n    Explanation\n    In this code, we first create a 4x4 array of ones using np.ones((4, 4)). Then, we use np.pad to add a border of zeros around the array. The ((1, 1), (1, 1)) parameter specifies the amount of padding to add on each side of the array. The mode='constant' parameter ensures that zeros are used for padding. The resulting array transformed_arr has the desired transformation, where the original array is padded with zeros on all sides.\n"