Yup I am on Day 4

today is about np.arange( ) and np.eye( )

1. *The np.arange() function is a NumPy function that creates a new 1-dimensional array with evenly spaced values within a specified range. It allows you to generate a sequence of numbers based on a start, stop, and step size.*

Here's the general syntax of np.arange() --> np.arange(start, stop, step, dtype=None)

Let's break down the parameters:

start: The start value of the sequence. It is inclusive in the sequence.
stop: The end value of the sequence. It is exclusive in the sequence.
step: The step size or the increment between consecutive values in the sequence. The default is 1.
dtype (optional): The data type of the elements in the array. If not provided, it will be determined based on the other parameters.
The np.arange() function returns a new 1-dimensional array that contains the values from start to stop-1, incremented by step.

2. *The np.eye() function is a NumPy function that creates a new 2-dimensional array (matrix) with ones on the diagonal and zeros elsewhere. It is commonly used to create identity matrices.*

Here's the general syntax of np.eye() --> np.eye(N, M=None, k=0, dtype=float, order='C')

Let's break down the parameters:

N: The number of rows in the resulting matrix.
M (optional): The number of columns in the resulting matrix. If not provided, it defaults to N, creating a square matrix.
k (optional): The index of the diagonal. The default is 0, which refers to the main diagonal. Positive values refer to diagonals above the main diagonal, and negative values refer to diagonals below the main diagonal.
dtype (optional): The data type of the elements in the array. The default is float.
order (optional): The memory layout of the array. It can be 'C' for row-major (C-style) or 'F' for column-major (Fortran-style). The default is 'C'.
The np.eye() function returns a new 2-dimensional array (matrix) where the elements on the diagonal are ones, and all other elements are zeros.

Lets solve some examples

1. Using Numpy create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]

In [2]:
import numpy as np 

print(np.arange(10,100,1)) # by default index value is 1 (3rd paramter) no need it mention again if it's 1 . it's upto you 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


2. Using Numpy create the following array:
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

In [3]:
import numpy as np

# Create a 1-dimensional array with values from 10 to 99
arr = np.arange(10, 100)
# Reshape the array into a 2-dimensional array with shape (9, 10)
result = arr.reshape(9, 10)

print(result)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


3. Using Numpy create a 6x6 two-dimensional array - identity matrix with int data type. Print this array to the console as shown below.
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

In [4]:
import numpy as np

# Create a 6x6 identity matrix with int data type
arr = np.eye(6, dtype=int)

# Print the array
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
